# Generated by Django 2.1 on 2018-10-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='group',
            field=models.ManyToManyField(to='contacts.Group'),
        ),
    ]
