# Generated by Django 2.1 on 2018-10-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20181031_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
