# Generated by Django 2.1 on 2018-10-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20181031_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='profile_images/'),
        ),
    ]
